# GoReleaser configuration for TomcatKit
# Documentation: https://goreleaser.com

version: 2

project_name: tomcatkit

before:
  hooks:
    - go mod tidy

builds:
  - id: tomcatkit
    main: ./cmd/tomcatkit
    binary: tomcatkit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz
    files:
      - README.md
      - README_KR.md
      - README_JP.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "typo"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: playok
    name: TomcatKit
  draft: false
  prerelease: auto
  name_template: "TomcatKit v{{.Version}}"

# Homebrew formula (optional, for future use)
# brews:
#   - repository:
#       owner: playok
#       name: homebrew-tap
#     homepage: "https://github.com/playok/TomcatKit"
#     description: "CLI-based TUI utility for Apache Tomcat 9.0 configuration management"
#     license: "MIT"
